services:
  todo-app:
    image: golang:1.24.6-bookworm
    working_dir: /app
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/app 
    env_file:
      - ./.env
    command: go run cmd/main.go 

    