package config

type Env string

const (
	GOOGLE_AUTH_URL      Env = "GOOGLE_AUTH_URL"
	GOOGLE_CLIENT_SECRET Env = "GOOGLE_CLIENT_SECRET"
	GOOGLE_CLIENT_ID     Env = "GOOGLE_CLIENT_ID"
	GOOGLE_REDIRECT_URL  Env = "GOOGLE_REDIRECT_URL"
	GOOGLE_SCOPE         Env = "GOOGLE_SCOPE"
)
