package config

const (
	GOOGLE_AUTH_URL      = "GOOGLE_AUTH_URL"
	GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET"
	GOOGLE_CLIENT_ID     = "GOOGLE_CLIENT_ID"
	GOOGLE_REDIRECT_URL  = "GOOGLE_REDIRECT_URL"
	GOOGLE_SCOPE         = "GOOGLE_SCOPE"
)
